
cloud:
  aws:
    region:
      static: ap-southeast-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: "****"
      secret-key: "****"
server:
  port: 9004

integration:
  aws-sqs:
    region: "ap-southeast-3"
    access-key: "****"
    secret-key: "****"
    queue-url: "https://sqs.ap-southeast-3.amazonaws.com/735185491450/kezbek-notification-email"
    queue-name: "kezbek-notification-email"
