
cloud:
  aws:
    region:
      static: ap-southeast-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: "AKIA2WLDYKX5GR7IAI66"
      secret-key: "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"
server:
  port: 9004

integration:
  aws-sqs:
    region: "ap-southeast-3"
    access-key: $ACCESS_KEY
    secret-key: $SECRET_KEY
    queue-url: "https://sqs.ap-southeast-3.amazonaws.com/735185491450/kezbek-notification-email"
    queue-name: "kezbek-notification-email"